# Generated by Django 5.1.3 on 2024-11-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_user_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_type',
            new_name='person_type',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='reviewer',
            new_name='from_person',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='reviewee',
            new_name='to_person',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='user',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_locations',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_fare',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rating_value',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='driver',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_license',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='feedback',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='pickup_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_route', to='backend.driver'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_schedule', to='backend.driver'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_value',
        ),
    ]
