# Generated by Django 5.1.3 on 2024-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_booking_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timing',
            field=models.CharField(default='', max_length=20),
        ),
    ]
