# Generated by Django 5.1.3 on 2024-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_schedule_departure_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='schedule',
        ),
        migrations.AddField(
            model_name='driver',
            name='timing',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
