# Generated by Django 5.1.3 on 2024-12-03 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_driver_schedule_driver_timing_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 03 and be 11 digits', regex='^03\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
